name: CI

on:
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    name: ✅ Unit & integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Cache
        uses: coursier/cache-action@v6.1
      - name: Setup GraalVM environment
        uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: '21.2.0'
          java: 'java11'
      - name: Install python
        run: gu install python
      - name: Python environment
        run: graalpython -m venv ${JAVA_HOME}/languages/python/scala-pygments/
      - name: Install pygments
        run: ${JAVA_HOME}/languages/python/scala-pygments/bin/pip install Pygments
      - name: Tests
        run: sbt +test +It/test
  lint:
    name: ⚠️ Fatal warnings and code formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Cache
        uses: coursier/cache-action@v6.1
      - name: Setup GraalVM environment
        uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: '21.2.0'
          java: 'java11'
      - name: Code formatting
        run: sbt scalafmtCheckAll
      - name: Fatal warnings
        run: sbt -Dmode=strict +compile